Data Encoding Techniques

1. Nominal/OHE(One-Hot-Encoding) Technique
2. Lable and Ordinal Encoding
3. Target Guided Ordinal Encoding

1. Nominal/ One Hot Encoding 

This data encoding technique will create new features based on the number of categories that we have and place 1 if it is present in this row or 0 if not present

example: dress_color field has - [Red, Greeen, Blue] then we create 3 new features Red, Green and Blue and put 1 and rest all 0's

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [5]:
df = pd.DataFrame({'color': ['red', 'blue', 'green', 'blue', 'red']})
df.head()

   color
0    red
1   blue
2  green
3   blue
4    red

In [6]:
# Create a instance of OneHotEncoder
encoder = OneHotEncoder()

In [18]:
# Fit and transform the data
encoded = encoder.fit_transform(df[['color']]).toarray()

In [12]:
import pandas as pd
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['color']))
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         1.0          0.0        0.0
4         0.0          0.0        1.0

In [14]:
encoder.transform([['blue']]).toarray()

d:\AI-Learnings\Machine_Learning\Feature_Engineering\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [16]:
pd.concat([df, encoder_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3   blue         1.0          0.0        0.0
4    red         0.0          0.0        1.0

Example Working on tips dataset

In [29]:
import seaborn as sns
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [22]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']

In [24]:
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['day']]).toarray()

In [26]:
encoder.get_feature_names_out()

array(['day_Fri', 'day_Sat', 'day_Sun', 'day_Thur'], dtype=object)

In [28]:
encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out()
)
encoded_df.head()

   day_Fri  day_Sat  day_Sun  day_Thur
0      0.0      0.0      1.0       0.0
1      0.0      0.0      1.0       0.0
2      0.0      0.0      1.0       0.0
3      0.0      0.0      1.0       0.0
4      0.0      0.0      1.0       0.0

In [30]:
df_final = pd.concat([df, encoded_df], axis=1)

df_final.head()

,total_bill,tip,sex,smoker,day,time,size,day_Fri,day_Sat,day_Sun,day_Thur
0,16.99,1.01,Female,No,Sun,Dinner,2,0.0,0.0,1.0,0.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0.0,0.0,1.0,0.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0.0,0.0,1.0,0.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0.0,0.0,1.0,0.0
4,24.59,3.61,Female,No,Sun,Dinner,4,0.0,0.0,1.0,0.0

Label Encoding 

This method assigns a unique numerical values for the categorical data

In [31]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [33]:
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'blue', 'red']})
df.head()

   color
0    red
1   blue
2  green
3   blue
4    red

In [35]:
lbl_encoder.fit_transform(df[['color']])

d:\AI-Learnings\Machine_Learning\Feature_Engineering\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 0, 2])

In [39]:
lbl_encoder.transform([['red']])

d:\AI-Learnings\Machine_Learning\Feature_Engineering\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [41]:
lbl_encoder.transform([['blue']])

d:\AI-Learnings\Machine_Learning\Feature_Engineering\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

The problem with this method is when we assign unique labels our model may start thinking red may have a higher capacity value because red has 2 which is higher when compared to green(1) and blue(0)

so we move from nominal to ordinal data

Ordinal Data Encoding

In Ordinal Data Encoding Technique the numeric values are assigned based on its position in the order

In [43]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [45]:
df= pd.DataFrame({'size': ['small', 'medium', 'large', 'medium', 'small']})
df.head()

     size
0   small
1  medium
2   large
3  medium
4   small

In [49]:
ordinal_encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])
ordinal_encoded = ordinal_encoder.fit_transform(df[['size']])
ordinal_encoded

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.]])